run:
  allow-parallel-runners: false

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  lll:
    line-length: 120
  maligned:
    suggest-new: true
  misspell:
    locale: US
  govet:
    check-shadowing: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - gocyclo
    - gofmt
    - goprintffuncname
    - interfacer
    - misspell
    - nolintlint
    - rowserrcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - varcheck